### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jprochazk** [jprochazk/twitch-irc-benchmarks#15]
Hi, if you're receiving this notification, it's because I forgot to include a license and I'm now asking you to agree to dual-license your contribution to this repo under `MIT` and `Apache 2.0`. Your contributions still belong to you, and it's legal to redistribute them due to GitHub's TOS, but it isn't legal for me to modify them 4Head.

If you agree, reply with the following message:
```
I give permission for my contributions to `twitch-irc-benchmarks` to be dual-licensed under MIT and Apache-2.0.
```

If you don't agree, reply with something along these lines:
```
I don't give permission for my contributions to `twitch-irc-benchmarks` to be dual-licensed under MIT and Apache-2.0
```

Contributors:
- [x] @badoge 
- [x] @Foretack 
- [x] @neon-sunset 
- [x] @treuks 
- [x] @rod41732 
- [x] @ilya-zlobintsev 

Thanks!

**Comment by badoge** [comment]
I give permission for my contributions to `twitch-irc-benchmarks` to be dual-licensed under MIT and Apache-2.0.

**Comment by Foretack** [comment]
I give permission for my contributions to `twitch-irc-benchmarks` to be dual-licensed under MIT and Apache-2.0.

**Comment by ilya-zlobintsev** [comment]
I give permission for my contributions to `twitch-irc-benchmarks` to be dual-licensed under MIT and Apache-2.0.
cringe

**Comment by rod41732** [comment]
I give permission for my contributions to twitch-irc-benchmarks to be dual-licensed under MIT and Apache-2.0.

**Comment by treuks** [comment]
I give permission for my contributions to twitch-irc-benchmarks to be dual-licensed under MIT and Apache-2.0.

**Comment by neon-sunset** [comment]
I hereby notify that *feet*licker is licensed under `Unlicense` therefore requires no attribution. Fine, however, I give permission for my contributions to twitch-irc-benchmarks to be dual-licensed under MIT and Apache-2.0.

**Comment by jprochazk** [comment]
🚀 blazingly fast
